
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 300MB
  profiles:
    active: deploy

jwt:
  issuer: ajufresh@gmail.com
  secret_key: ${JWT_SECRET}
  accessTokenExpiration: 3600000 #1시간
  #refreshTokenExpiration: 1209600000 #2주
kakao:
  client_id: ${KAKAO_API_KEY}
  redirect_uri: ${REDIRECT_URI}

cloud:
  aws:
    s3:
      bucket: pleanet  # S3 버킷명
    region:
      static: ap-northeast-2   # 서울 리전
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}

openai:
  api-key: ${OPENAI_API_KEY}