spring:
  datasource:
    url: jdbc:mysql://pleanet-dev.cn8022w8auqm.ap-northeast-2.rds.amazonaws.com:3306/pleanet
    username: 'root'
    password: 'odeng00!1'
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000